---
- name: "breaking-change"
  color: ee0701
  description: "A change that changes the API or breaks backward compatibility for users."
- name: "bug"
  color: ee0701
  description: "Inconsistencies or issues which will cause a problem for users or implementors."
- name: "documentation"
  color: 0052cc
  description: "Solely about the documentation of the project."
- name: "enhancement"
  color: 1d76db
  description: "New features, options, or other additions."


- name: "in-progress"
  color: fbca04
  description: "Issue is currently being worked on by a developer."
- name: "stale"
  color: fef2c0
  description: "No activity for quite some time."
- name: "no-stale"
  color: fef2c0
  description: "This is exempt from the stale bot."

- name: "invalid"
  color: fef2c0
  description: "Missing information, off-topic, spam, or otherwise doesn't apply to this project."

- name: "beginner-friendly"
  color: 0e8a16
  description: "Good first issue for people wanting to contribute to this project."
- name: "help-wanted"
  color: 0e8a16
  description: "We want to add this to the project. Contributions welcome!"

- name: "priority-critical"
  color: ee0701
  description: "Must be addressed as soon as possible."
- name: "priority-high"
  color: b60205
  description: "After critical issues are fixed, these should be dealt with before any further issues."
- name: "priority-medium"
  color: 0e8a16
  description: "This issue may be useful, and needs some attention."
- name: "priority-low"
  color: e4ea8a
  description: "Nice addition, maybe... someday..."
