[input]
base_directory = ""
url_prefix = "https://docs.cweagans.net/composer-configurable-plugin"
frontmatter_handling = "Omit"
files = [
    {path = "_index.md", url = "/", title = "Composer Configurable Plugin"},
    {path = "project/code-of-conduct.md", url = "/project/code-of-conduct/", title = "Code of Conduct"},
    {path = "project/contributing.md", url = "/project/contributing/", title = "Contributing"},
    {path = "project/security.md", url = "/project/security/", title = "Security"},
    {path = "usage/implementation.md", url = "/usage/implementation/", title = "Implementation"},
    {path = "usage/overview.md", url = "/usage/overview/", title = "Overview"},
]
